DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS tool_executions;
DROP TABLE IF EXISTS credentials;
DROP TABLE IF EXISTS flows;
DROP TABLE IF EXISTS mcp_projects;
DROP TABLE IF EXISTS workspaces;
DROP TABLE IF EXISTS users;
